name: Call a reusable workflow and use its outputs

on:
  workflow_dispatch:

jobs:
  job1:
    uses: robert-s-lee/gha-workflow-chain/.github/workflows/workflow1.yaml@main

  job2:
    needs: job1
    uses: robert-s-lee/gha-workflow-chain/.github/workflows/workflow2.yaml@main
    with:
      firstword1: {{ needs.job1.outputs.firstword }}
      secondword1: ${{ needs.job1.outputs.secondword }}

  job3:
    runs-on: ubuntu-latest
    needs: job2
    steps:
      - run: echo ${{ needs.job1.outputs.firstword }} ${{ needs.job1.outputs.secondword }}
      - run: echo ${{ needs.job2.outputs.firstword }} ${{ needs.job2.outputs.secondword }}
