name: workflow1

on:
  workflow_call:
    # Map the workflow outputs to job outputs
    outputs:
      firstword:
        description: "The first output string"
        value: ${{ jobs.example_job.outputs.output1 }}
      secondword:
        description: "The second output string"
        value: ${{ jobs.example_job.outputs.output2 }}  
  
jobs:
  example_job:
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        os: [ubuntu-latest] #, macos-latest,windows-latest]
        python-version: [3.8, 3.9]       
        python-venv: [""] #,"venv"]
        byoc-cost-savings: ["--cost-savings"] #, ""]
        byoc-region: ["us-east-1"]       
        byoc-instance-types: ["--instance-types t2.medium,g4dn.xlarge"] 
    name: Generate output
    runs-on: ubuntu-latest   
    # Map the job outputs to step outputs
    outputs:
      output1: ${{ steps.step1.outputs.firstword }}
      output2: ${{ steps.step2.outputs.secondword }}
    steps:
      - id: step1
        run: echo "::set-output name=firstword::${{matrix.python-version}}"
      - id: step2
        run: echo "::set-output name=secondword::${{matrix.os}}"